extra["groupName"] = "net.toliner.korgelin"
extra["modVersion"] = "1.1.0-rei.1"
extra["modName"] = "Korgelin"
extra["kotlinVersion"] = "1.4.31"
extra["annotationsVersion"] = "20.1.0"
extra["coroutineVersion"] = "1.4.2"
extra["serializationVersion"] = "0.20.0"
